### ISSUE TITLE
jvm.dll path not detected in JDK 8

### ISSUE THREAD

**Issue by KenyOS** [Bill-Stewart/ApacheTomcatSetup#3]
In this part of your code on [https://github.com/Bill-Stewart/ApacheTomcatSetup/blob/master/Messages-en.isl](https://github.com/Bill-Stewart/ApacheTomcatSetup/blob/master/Messages-en.isl)
`ErrorJVMOldGUIMessage=The selected jvm.dll file is version %1, but {#AppName} requires at least Java %2.%n%nYou must select a jvm.dll file that meets the minimum version requirement.`

I'm getting this message about "minimum version requirement" but I'm using the right version of Java ( ver. 8 ).
From this installer: `OpenJDK8U-jdk_x64_windows_hotspot_8u362b09.msi`

I noticed that where should show me version of java installed '%1', instead is returning an empty value for some reason. Could you help me?

Thank you in advance and great work on this installer and doc. It will help me a ton!

**Comment by Bill-Stewart** [comment]
Sorry for the issue. I'll try and get this fixed before the next version. In the meantime you can work around this by using the `/jvmpath` command-line parameter; for example:

    apache-tomcat-9.0.72-setup.exe /jvmpath="C:\Program Files\Eclipse Adoptium\JDK8\jre\bin\server\jvm.dll"

**Comment by Bill-Stewart** [comment]
The issue is that the installer assumed that `jvm.dll` was in _javahome_`\bin\server`. It seems that's not the case with some versions of the JDK, where the path was changed to _javahome_`\jre\bin\server`. I don't know when this changed, as older builds of JDK8 (for example) use the old path (without the `jre` subdirectory).

Due to this nuisance of the changed path, I released a new version of `JavaInfo.dll` with a new `GetJavaJVMPath()` function that looks in both places for `jvm.dll` and updated the installer accordingly. The fix will be in the next version.

In the meantime: If the installer can't find `jvm.dll`, you'll need to find it on your disk and specify the path with the `/jvmpath` parameter like the example in the previous post in this thread.

**Comment by KenyOS** [comment]
thank you for your time. I'll do another test tomorrow in my setup installation. I'm also using Inno installer

**Comment by KenyOS** [comment]
`/jvmpath` definetely solved my issue, tomcat is working now. Thank you @Bill-Stewart

**Comment by Bill-Stewart** [comment]
FYI this should be fixed in 9.0.73 (just released).
